version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    command: uvicorn main:api --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
     build: ./frontend
     volumes:
       - ./frontend:/app
     ports:
       - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
